(function(){
'use strict';
let idleTimer=null,lastActivity=Date.now(),employeeBuilt=false,weeklyBuilt=false,weeklyBusy=false;
const touch=()=>{lastActivity=Date.now()};
['mousemove','mousedown','keydown','touchstart','scroll','click'].forEach(e=>document.addEventListener(e,touch,{passive:true}));
function isEmployee(){return typeof profile!=='undefined'&&!!profile&&profile.rol!=='administrador'}
function isAdmin(){return typeof profile!=='undefined'&&!!profile&&profile.rol==='administrador'}
function money(v){return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v||0))}
function text(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;')}
function injectEmployeeCss(){if(document.getElementById('mahe-employee-css'))return;const s=document.createElement('style');s.id='mahe-employee-css';s.textContent=`
.employee-only-clock{margin-bottom:15px!important;text-align:center!important}.employee-only-clock h2{text-align:left!important;margin-top:0}.employee-only-clock .sub{color:#9ba5b1;text-align:left;margin-bottom:14px}.employee-round{width:220px!important;height:220px!important;border-radius:50%!important;border:7px solid #16845e!important;background:#151a20!important;color:#fff!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:8px!important;font-size:19px!important;font-weight:900!important;margin:16px auto 12px!important;transition:.2s!important;box-shadow:0 0 0 1px #0008,0 8px 25px #0008!important}.employee-round:hover{transform:scale(1.02)!important}.employee-round.out{border-color:#a73e3b!important}.employee-round:disabled{opacity:.65!important}.employee-round .ico{font-size:38px!important;line-height:1}.employee-round .txt{max-width:180px!important;line-height:1.15!important}.employee-greeting{min-height:30px;font-size:22px;font-weight:900;color:#65e3b0;text-align:center;margin:5px 0 12px}.employee-greeting.rest{color:#f5b942}.employee-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;max-width:560px;margin:0 auto 8px}.employee-period{color:#9ba5b1;font-size:13px;margin:2px 0 8px}.employee-summary-card{background:#1c2229;border:1px solid #303842;border-radius:13px;padding:14px;text-align:center}.employee-summary-card span{display:block;color:#9ba5b1;font-size:13px;margin-bottom:5px}.employee-summary-card b{font-size:24px}.employee-note{color:#9ba5b1;font-size:12px;margin-top:6px}@media(max-width:520px){.employee-round{width:190px!important;height:190px!important}.employee-summary{grid-template-columns:1fr}.employee-round .txt{font-size:17px}}
`;document.head.appendChild(s)}
function startIdle(){if(idleTimer)return;lastActivity=Date.now();idleTimer=setInterval(async()=>{if(typeof profile!=='undefined'&&profile&&Date.now()-lastActivity>=300000){clearInterval(idleTimer);idleTimer=null;try{await db.auth.signOut()}catch(e){}alert('Tu sesión se cerró por 5 minutos de inactividad. Debes ingresar nuevamente.');location.reload()}},1000)}
function greeting(s,rest){const g=document.getElementById('employeeGreeting');if(!g)return;g.textContent=s;g.className='employee-greeting '+(rest?'rest':'');clearTimeout(window._maheGreeting);window._maheGreeting=setTimeout(()=>{if(g)g.textContent=''},5000)}
function currentEmployee(){if(!isEmployee()||!Array.isArray(employees))return null;const id=profile.empleado_id;return employees.find(e=>String(e.id)===String(id))||null}
function currentOpen(){const e=currentEmployee();return e&&Array.isArray(journeys)?journeys.find(j=>String(j.empleado_id)===String(e.id)&&!j.salida):null}
function openEmployeeIds(){const ids=new Set();for(const j of (Array.isArray(journeys)?journeys:[])){if(!j.salida&&j.empleado_id)ids.add(String(j.empleado_id))}return ids}
function buttonState(){const b=document.getElementById('employeeRound');if(!b)return;const open=currentOpen();b.classList.toggle('out',!!open);const i=b.querySelector('.ico'),t=b.querySelector('.txt');if(i)i.textContent=open?'⏹️':'▶️';if(t)t.textContent=open?'REGISTRAR SALIDA':'REGISTRAR ENTRADA'}
function adminOpenCount(){if(!isAdmin())return;const el=document.getElementById('stOpen');if(el)el.textContent=String(openEmployeeIds().size)}
function fallbackSummary(e){const rows=(Array.isArray(journeys)?journeys:[]).filter(j=>String(j.empleado_id)===String(e.id));let hours=0,total=0;for(const j of rows){let h=Number(j.horas_pagadas||j.horas_calculadas||0);if(!j.salida&&j.entrada)h=Math.max(0,(Date.now()-new Date(j.entrada).getTime())/3600000);hours+=h;total+=Number(j.total_pago||0)}return{periodo_inicio:rows.length?rows[rows.length-1].fecha:'',periodo_fin:new Date().toISOString().slice(0,10),horas:hours,total:total}}
async function employeeSummary(){if(!isEmployee())return;const e=currentEmployee(),box=document.getElementById('employeeSummary');if(!e||!box)return;try{let s=null;const r=await db.rpc('resumen_pago_semanal',{p_empleado_id:e.id});if(!r.error&&r.data&&r.data[0])s=r.data[0];if(!s)s=fallbackSummary(e);box.innerHTML='<div class="employee-period">Periodo actual: '+text(s.periodo_inicio||'')+' → '+text(s.periodo_fin||'')+'</div><div class="employee-summary"><div class="employee-summary-card"><span>🕐 Horas acumuladas</span><b>'+Number(s.horas||0).toFixed(2)+' h</b></div><div class="employee-summary-card"><span>💵 Pago acumulado</span><b>'+money(s.total)+'</b></div></div>'}catch(err){const s=fallbackSummary(e);box.innerHTML='<div class="employee-period">Periodo actual</div><div class="employee-summary"><div class="employee-summary-card"><span>🕐 Horas acumuladas</span><b>'+Number(s.horas||0).toFixed(2)+' h</b></div><div class="employee-summary-card"><span>💵 Pago acumulado</span><b>'+money(s.total)+'</b></div></div>'}}
async function employeeClick(){const e=currentEmployee();const b=document.getElementById('employeeRound');if(!e||!b)return alert('No se encontró el empleado asociado a esta cuenta.');const open=!!currentOpen();b.disabled=true;try{if(typeof window.clock==='function'){await window.clock(e.id,open?'SALIDA':'ENTRADA')}else{const r=await db.rpc('registrar_movimiento_personal',{p_empleado_id:e.id,p_tipo:open?'SALIDA':'ENTRADA',p_observacion:null});if(r.error)throw r.error}touch();greeting(open?'¡Feliz descanso! 😴':'¡Feliz turno! 👋',open);await loadAll();buttonState();await employeeSummary()}catch(err){alert(err?.message||'No se pudo registrar el movimiento.')}finally{b.disabled=false}}
function buildEmployee(){if(!isEmployee())return;injectEmployeeCss();const area=document.getElementById('employeeArea');if(!area)return;if(!employeeBuilt){employeeBuilt=true;document.querySelector('.stats')?.classList.add('hidden');document.getElementById('adminArea')?.classList.add('hidden');document.getElementById('movementCard')?.classList.add('hidden');document.querySelectorAll('#app>.card.full').forEach(x=>x.classList.add('hidden'));area.className='card employee-only-clock';area.innerHTML='<h2>Mi jornada</h2><div class="sub">Aquí puedes ver tus horas acumuladas y el valor que llevas pendiente de pago.</div><button id="employeeRound" class="employee-round" type="button"><span class="ico">▶️</span><span class="txt">REGISTRAR ENTRADA</span></button><div id="employeeGreeting" class="employee-greeting" aria-live="polite"></div><div id="employeeSummary"></div><div id="employeeSelf" class="hidden" aria-hidden="true"></div><div class="employee-note">El valor de la hora no se muestra. Aquí solo ves lo que llevas acumulado.</div>';document.getElementById('employeeRound').addEventListener('click',employeeClick)}buttonState();employeeSummary()}
async function paymentSummary(id){const r=await db.rpc('resumen_pago_semanal',{p_empleado_id:id});if(r.error)throw r.error;return r.data&&r.data[0]?r.data[0]:{periodo_inicio:'',periodo_fin:'',horas:0,total:0}}
async function refreshWeekly(){if(weeklyBusy||!isAdmin())return;const grid=document.getElementById('weeklyGrid');if(!grid)return;weeklyBusy=true;grid.innerHTML='';const list=Array.from(new Map((employees||[]).filter(e=>e&&e.activo!==false).map(e=>[String(e.id),e])).values());for(const e of list){const c=document.createElement('div');c.className='weekly-card';try{const s=await paymentSummary(e.id),h=Number(s.horas||0),t=Number(s.total||0);c.innerHTML='<div class="wn">'+text(e.nombre_completo)+'</div><div class="wd">Periodo abierto: '+text(s.periodo_inicio||'')+' → '+text(s.periodo_fin||'')+'</div><div class="wh">'+h.toFixed(2)+' horas</div><div class="wh">'+money(t)+'</div><button '+(h<=0?'disabled':'')+'>PAGADO ✓</button>';const btn=c.querySelector('button');btn.onclick=async()=>{const fresh=await paymentSummary(e.id),fh=Number(fresh.horas||0),ft=Number(fresh.total||0);if(fh<=0)return alert('No hay horas pendientes de pago para '+e.nombre_completo+'.');if(!confirm('¿Pagar a '+e.nombre_completo+' ahora?\n\nHoras: '+fh.toFixed(2)+'\nTotal: '+money(ft)+'\n\nAl confirmar, este período se cierra y el nuevo conteo comienza desde cero.'))return;btn.disabled=true;const r=await db.rpc('pagar_semana_empleado',{p_empleado_id:e.id,p_observacion:'Pago realizado por administrador'});if(r.error){alert('No se pudo registrar el pago: '+r.error.message);btn.disabled=false;return}alert('Pago registrado correctamente. El nuevo conteo comenzó desde cero.');await loadAll();await refreshWeekly()};grid.appendChild(c)}catch(err){c.innerHTML='<div class="wn">'+text(e.nombre_completo)+'</div><div class="wd">No se pudo calcular el acumulado.</div>';grid.appendChild(c)}}if(!list.length)grid.innerHTML='<div class="weekly-sub">No hay empleados activos.</div>';weeklyBusy=false}
function buildWeekly(){if(!isAdmin()||weeklyBuilt)return;const target=document.getElementById('adminArea');if(!target)return;weeklyBuilt=true;const box=document.createElement('section');box.className='weekly-pay';box.id='weeklyPay';box.innerHTML='<h2>💰 Pago de personal</h2><div class="weekly-sub">Puedes pagar cuando quieras. <b>PAGADO</b> cierra el período actual sin borrar el histórico y comienza un nuevo conteo desde cero.</div><div id="weeklyGrid" class="weekly-grid"><div class="weekly-sub">Calculando...</div></div>';target.parentNode.insertBefore(box,target);refreshWeekly()}
function tick(){if(typeof profile==='undefined'||!profile)return;startIdle();if(isEmployee())buildEmployee();if(isAdmin())buildWeekly();buttonState();adminOpenCount()}
const baseLoad=window.loadAll;if(typeof baseLoad==='function'){window.loadAll=async function(){const r=await baseLoad.apply(this,arguments);setTimeout(()=>{tick();if(isAdmin())refreshWeekly();if(isEmployee())employeeSummary()},80);return r}}
const waiter=setInterval(()=>{if(typeof profile!=='undefined'&&profile){clearInterval(waiter);tick()}},200);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')touch()});
})();