(function(){
'use strict';
let idleTimer=null,lastActivity=Date.now(),employeeBuilt=false,weeklyBuilt=false,weeklyRun=0,weeklyBusy=false;
const touch=()=>{lastActivity=Date.now()};
['mousemove','mousedown','keydown','touchstart','scroll','click'].forEach(e=>document.addEventListener(e,touch,{passive:true}));
function isEmployee(){return typeof profile!=='undefined'&&!!profile&&profile.rol!=='administrador'}
function isAdmin(){return typeof profile!=='undefined'&&!!profile&&profile.rol==='administrador'}
function money(v){return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v||0))}
function text(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;')}
function startIdle(){if(idleTimer)return;lastActivity=Date.now();idleTimer=setInterval(async()=>{if(typeof profile!=='undefined'&&profile&&Date.now()-lastActivity>=300000){clearInterval(idleTimer);idleTimer=null;try{await db.auth.signOut()}catch(e){}alert('Tu sesión se cerró por 5 minutos de inactividad. Debes ingresar nuevamente.');location.reload()}},1000)}
function greeting(s,rest){const g=document.getElementById('employeeGreeting');if(!g)return;g.textContent=s;g.className='employee-greeting '+(rest?'rest':'');clearTimeout(window._maheGreeting);window._maheGreeting=setTimeout(()=>g.textContent='',5000)}
function currentEmployee(){if(!isEmployee()||!Array.isArray(employees))return null;const id=profile.empleado_id;return employees.find(e=>String(e.id)===String(id))||null}
function openEmployeeIds(){const ids=new Set();for(const j of (Array.isArray(journeys)?journeys:[])){if(!j.salida&&j.empleado_id)ids.add(String(j.empleado_id))}return ids}
function buttonState(){const b=document.getElementById('employeeRound');if(!b||!Array.isArray(journeys))return;const e=currentEmployee();const open=!!e&&journeys.some(j=>String(j.empleado_id)===String(e.id)&&!j.salida);b.classList.toggle('out',open);const i=b.querySelector('.ico'),t=b.querySelector('.txt');if(i)i.textContent=open?'⏹️':'▶️';if(t)t.textContent=open?'REGISTRAR SALIDA':'REGISTRAR ENTRADA'}
function adminOpenCount(){if(!isAdmin())return;const el=document.getElementById('stOpen');if(el)el.textContent=String(openEmployeeIds().size)}
async function employeeSummary(){if(!isEmployee())return;const e=currentEmployee(),box=document.getElementById('employeeSummary');if(!e||!box)return;try{const r=await db.rpc('resumen_pago_semanal',{p_empleado_id:e.id});if(r.error)throw r.error;const s=r.data&&r.data[0]?r.data[0]:{};box.innerHTML='<div class="employee-period">Periodo actual: '+text(s.periodo_inicio||'')+' → '+text(s.periodo_fin||'')+'</div><div class="employee-summary"><div class="employee-summary-card"><span>🕐 Horas acumuladas</span><b>'+Number(s.horas||0).toFixed(2)+' h</b></div><div class="employee-summary-card"><span>💵 Pago acumulado</span><b>'+money(s.total)+'</b></div></div>'}catch(e){box.innerHTML='<div class="weekly-sub">No se pudo cargar el acumulado.</div>'}}
function buildEmployee(){if(!isEmployee()||employeeBuilt)return;const area=document.getElementById('employeeArea');if(!area)return;employeeBuilt=true;document.querySelector('.stats')?.classList.add('hidden');document.getElementById('adminArea')?.classList.add('hidden');document.getElementById('movementCard')?.classList.add('hidden');document.querySelectorAll('#app>.card.full').forEach(x=>x.classList.add('hidden'));area.className='card employee-only-clock';area.innerHTML='<h2>Mi jornada</h2><div class="sub">Aquí puedes ver tus horas acumuladas y el valor que llevas pendiente de pago.</div><div id="employeeSummary"></div><button id="employeeRound" class="employee-round" type="button"><span class="ico">▶️</span><span class="txt">REGISTRAR ENTRADA</span></button><div id="employeeGreeting" class="employee-greeting" aria-live="polite"></div>';buttonState();employeeSummary();const b=document.getElementById('employeeRound');b.onclick=async()=>{const e=currentEmployee();if(!e)return alert('No se encontró el empleado asociado a esta cuenta.');const open=Array.isArray(journeys)&&journeys.some(j=>String(j.empleado_id)===String(e.id)&&!j.salida);b.disabled=true;const r=await db.rpc('registrar_movimiento_personal',{p_empleado_id:e.id,p_tipo:open?'SALIDA':'ENTRADA',p_observacion:null});if(r.error){alert(r.error.message||'No se pudo registrar el movimiento.');b.disabled=false;return}greeting(open?'¡Feliz descanso! 😴':'¡Feliz turno! 👋',open);touch();await loadAll();buttonState();await employeeSummary();b.disabled=false}}
async function paymentSummary(id){const r=await db.rpc('resumen_pago_semanal',{p_empleado_id:id});if(r.error)throw r.error;return r.data&&r.data[0]?r.data[0]:{periodo_inicio:'',periodo_fin:'',horas:0,total:0}}
async function refreshWeekly(){if(weeklyBusy||!isAdmin())return;const grid=document.getElementById('weeklyGrid');if(!grid)return;weeklyBusy=true;const run=++weeklyRun;grid.innerHTML='';const list=Array.from(new Map((employees||[]).filter(e=>e&&e.activo!==false).map(e=>[String(e.id),e])).values());for(const e of list){if(run!==weeklyRun)break;const c=document.createElement('div');c.className='weekly-card';try{const s=await paymentSummary(e.id),h=Number(s.horas||0),t=Number(s.total||0);c.innerHTML='<div class="wn">'+text(e.nombre_completo)+'</div><div class="wd">Periodo abierto: '+text(s.periodo_inicio||'')+' → '+text(s.periodo_fin||'')+'</div><div class="wh">'+h.toFixed(2)+' horas</div><div class="wh">'+money(t)+'</div><button '+(h<=0?'disabled':'')+'>PAGADO ✓</button>';const btn=c.querySelector('button');btn.onclick=async()=>{const fresh=await paymentSummary(e.id),fh=Number(fresh.horas||0),ft=Number(fresh.total||0);if(fh<=0)return alert('No hay horas pendientes de pago para '+e.nombre_completo+'.');if(!confirm('¿Pagar a '+e.nombre_completo+' ahora?\n\nHoras: '+fh.toFixed(2)+'\nTotal: '+money(ft)+'\n\nAl confirmar, este período se cierra y el nuevo conteo comienza desde cero.'))return;btn.disabled=true;const r=await db.rpc('pagar_semana_empleado',{p_empleado_id:e.id,p_observacion:'Pago realizado por administrador'});if(r.error){alert('No se pudo registrar el pago: '+r.error.message);btn.disabled=false;return}alert('Pago registrado correctamente. El nuevo conteo comenzó desde cero.');await loadAll();await refreshWeekly()};grid.appendChild(c)}catch(err){c.innerHTML='<div class="wn">'+text(e.nombre_completo)+'</div><div class="wd">No se pudo calcular el acumulado.</div>';grid.appendChild(c)}}if(!list.length)grid.innerHTML='<div class="weekly-sub">No hay empleados activos.</div>';weeklyBusy=false}
function buildWeekly(){if(!isAdmin()||weeklyBuilt)return;const target=document.getElementById('adminArea');if(!target)return;weeklyBuilt=true;const box=document.createElement('section');box.className='weekly-pay';box.id='weeklyPay';box.innerHTML='<h2>💰 Pago de personal</h2><div class="weekly-sub">Puedes pagar cuando quieras. <b>PAGADO</b> cierra el período actual sin borrar el histórico y comienza un nuevo conteo desde cero.</div><div id="weeklyGrid" class="weekly-grid"><div class="weekly-sub">Calculando...</div></div>';target.parentNode.insertBefore(box,target);refreshWeekly()}
function tick(){if(typeof profile==='undefined'||!profile)return;startIdle();if(isEmployee())buildEmployee();if(isAdmin())buildWeekly();buttonState();adminOpenCount()}
const oldLoad=typeof loadAll==='function'?loadAll:null;if(oldLoad){window.loadAll=async function(){const r=await oldLoad.apply(this,arguments);setTimeout(()=>{tick();if(isAdmin())refreshWeekly();if(isEmployee())employeeSummary()},100);return r}}
const waiter=setInterval(()=>{if(typeof profile!=='undefined'&&profile){clearInterval(waiter);tick()}},250);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')touch()});
})();